services:
  - type: web
    name: patient-health-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.8.0
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: healthcare_db
          property: connectionString
      - key: FLASK_APP
        value: app.py

  - type: database
    name: healthcare_db
    plan: free
    ipAllowList: []
