services:
  - type: web
    name: healthcare-data-system
    env: node
    plan: free
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: 18.17.0
      - key: DATABASE_URL
        sync: false
      - key: NEXTAUTH_SECRET
        value: "Esz8crWlkd1W/vNg/cAAzxJ39iGacADENEOU2b/zwKI="
      - key: NEXTAUTH_URL
        sync: false
    healthCheckPath: /
    autoDeploy: true
